### ISSUE TITLE
peer-to-peer-review

### ISSUE THREAD

**Issue by Apatakiti** [carlosmuerto/to-do-list-webpack#9]
You have done a great job but I suggest you add a local storage in the remove function.

**Comment by Aseadd** [comment]
Great Job 👍 

✔️ I think this part of the html is not necessary to test the DOM element   https://github.com/carlosmuerto/to-do-list-webpack/blob/a6cb6183166332fb768c316e4ba1f8a3878aba26/src/modules/__tests__/to-do-list.test.js#L24-L32

**Comment by carlosmuerto** [comment]
> Great Job 👍
> 
> ✔️ I think this part of the html is not necessary to test the DOM element
> 
> https://github.com/carlosmuerto/to-do-list-webpack/blob/a6cb6183166332fb768c316e4ba1f8a3878aba26/src/modules/__tests__/to-do-list.test.js#L24-L32

It is, to test the dom-manipulation function some parts of the HTML need to be mocked. 

![imagen](https://user-images.githubusercontent.com/34493013/185644631-12019b8b-4edb-4f33-b1cd-2cb9a96b8ca6.png)

**Comment by Aseadd** [comment]
Ok, What I was thinking is this part is enough
https://github.com/carlosmuerto/to-do-list-webpack/blob/a6cb6183166332fb768c316e4ba1f8a3878aba26/src/modules/__tests__/to-do-list.test.js#L34-L38

**Comment by carlosmuerto** [comment]
> Ok, What I was thinking is this part is enough
> 
> https://github.com/carlosmuerto/to-do-list-webpack/blob/a6cb6183166332fb768c316e4ba1f8a3878aba26/src/modules/__tests__/to-do-list.test.js#L34-L38

well, the template part is cloned to be added inside de `<ul>`
